### ISSUE TITLE
Not adding

### ISSUE THREAD

**Issue by w4rner** [mozilla/price-tracker#307] opened 2019-03-02 19:21 UTC
Not adding to Price Wise "cart". See Screen rec: https://www.dropbox.com/s/8x7kkhp2wkeip4w/pricewise.mov?dl=0

**Comment by biancadanforth** [comment] 2019-03-04 18:47
Thank you for filing this issue and for providing the recording.

What version of Firefox are you using? (Click "Firefox" on the top menu bar and then "About Firefox") What version of Price Wise? (Right click the toolbar icon and select "Manage Extension" to find this)

I am not able to reproduce this issue in the current release version, 65.0.1, in a new profile with the latest version of Price Wise (v21.0.0) is in the overflow menu as you have.

I am wondering if this might be overflow menu specific -- if you move the extension icon to the main toolbar menu instead of the overflow menu, do you still have this issue?

I noticed you have a lot of extensions installed; are all of your other extensions opening as expected that are also in the overflow menu? I am suspicious that this may be a Firefox bug rather than a Price Wise bug.
* For my future reference: [meta bug for Overflow menu display issues](https://bugzilla.mozilla.org/show_bug.cgi?id=1459046)

**Comment by w4rner** [comment] 2019-03-07 18:06
One I put it on main toolbar it worked again. Thanks.

**Comment by biancadanforth** [comment] 2019-04-10 20:21
Closing, as this is likely a Firefox bug, and there's not enough information here to identify if it is an existing or new Overflow menu bug.

**Closed by biancadanforth** 2019-04-10 20:21 UTC
